"""Agent adapter setup for AgentCanvas."""

from __future__ import annotations

import difflib
import json
import os
import shutil
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional

from . import __version__
from .ir import atomic_write_json, atomic_write_text, resolve_workspace


SUPPORTED_AGENTS = {"claude-code", "codex", "cursor", "antigravity", "generic", "auto"}
AGENT_UNDETECTED_EXIT = 4
CODEX_START = "<!-- agentcanvas:start -->"
CODEX_END = "<!-- agentcanvas:end -->"
OWNERSHIP_HEADER = "<!-- generated by agentcanvas init v%s - edits will be overwritten -->" % __version__
MCP_ENTRY = {
    "command": "uvx",
    "args": ["--from", "use-agentcanvas[mcp]", "agentcanvas", "mcp", "--workspace", "."],
}
CODEX_CONFIG_SNIPPET = """
[mcp_servers.agentcanvas]
command = "uvx"
args = ["--from", "use-agentcanvas[mcp]", "agentcanvas", "mcp", "--workspace", "."]
""".strip()


@dataclass(frozen=True)
class DetectionResult:
    agent: Optional[str]
    matches: Dict[str, List[str]]
    ambiguous: bool = False


class AdapterSetupError(ValueError):
    def __init__(self, code: str, message: str, *, details: Optional[Dict[str, Any]] = None) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "ok": False,
            "error": {
                "code": self.code,
                "message": self.message,
                "details": self.details,
            },
        }


def setup_adapter(
    workspace: str | Path,
    *,
    agent: str,
    env: Optional[Mapping[str, str]] = None,
    write_codex_config: bool = False,
    codex_config_path: Optional[str | Path] = None,
) -> Dict[str, Any]:
    root = resolve_workspace(workspace)
    selected = _normalize_agent(agent)
    detection = None
    if selected == "auto":
        detection = detect_agent(root, env=env)
        if not detection.agent:
            raise AdapterSetupError(
                "AGENT_UNDETECTED",
                "could not confidently detect the invoking agent",
                details={
                    "matches": detection.matches,
                    "ambiguous": detection.ambiguous,
                    "candidates": sorted(detection.matches),
                },
            )
        selected = detection.agent

    if selected == "claude-code":
        result = _setup_claude_code(root)
    elif selected == "codex":
        result = _setup_codex(
            root,
            write_codex_config=write_codex_config,
            codex_config_path=codex_config_path,
        )
    elif selected == "cursor":
        result = _setup_cursor(root)
    elif selected == "antigravity":
        result = _setup_antigravity(root)
    elif selected == "generic":
        result = _setup_generic(root)
    else:
        raise AdapterSetupError(
            "UNSUPPORTED_AGENT",
            "unsupported agent",
            details={"agent": agent, "supported": sorted(SUPPORTED_AGENTS)},
        )

    result["agent"] = selected
    result["workspace"] = str(root)
    result["detection"] = detection.__dict__ if detection else None
    return result


def detect_agent(workspace: str | Path, *, env: Optional[Mapping[str, str]] = None) -> DetectionResult:
    root = resolve_workspace(workspace)
    env = dict(os.environ if env is None else env)
    markers = _load_marker_data()
    matches: Dict[str, List[str]] = {}

    for marker in markers.get("env", []):
        agent = marker.get("agent")
        if not isinstance(agent, str):
            continue
        for key in marker.get("keys") or []:
            if isinstance(key, str) and key in env:
                matches.setdefault(agent, []).append("env:%s" % key)
        for prefix in marker.get("prefixes") or []:
            if not isinstance(prefix, str):
                continue
            found = sorted(key for key in env if key.startswith(prefix))
            if found:
                matches.setdefault(agent, []).extend("env:%s" % key for key in found)

    if len(matches) == 1:
        return DetectionResult(agent=next(iter(matches)), matches=matches)
    if len(matches) > 1:
        return DetectionResult(agent=None, matches=matches, ambiguous=True)

    for marker in markers.get("workspace", []):
        agent = marker.get("agent")
        if not isinstance(agent, str):
            continue
        for path in marker.get("paths") or []:
            if isinstance(path, str) and (root / path).exists():
                matches.setdefault(agent, []).append("path:%s" % path)
        for file_marker in marker.get("files") or []:
            if not isinstance(file_marker, Mapping):
                continue
            path = file_marker.get("path")
            contains = file_marker.get("contains")
            if not isinstance(path, str) or not isinstance(contains, str):
                continue
            file_path = root / path
            try:
                text = file_path.read_text(encoding="utf-8")
            except OSError:
                continue
            if contains in text:
                matches.setdefault(agent, []).append("file:%s contains %r" % (path, contains))

    if len(matches) == 1:
        return DetectionResult(agent=next(iter(matches)), matches=matches)
    return DetectionResult(agent=None, matches=matches, ambiguous=len(matches) > 1)


def render_skill_template() -> str:
    return _render_template("skill.md")


def _setup_claude_code(root: Path) -> Dict[str, Any]:
    skill_path = root / ".claude" / "skills" / "agentcanvas" / "SKILL.md"
    _write_text_if_changed(skill_path, render_skill_template())
    mcp_path = root / ".mcp.json"
    _merge_mcp_json(mcp_path)
    return {"ok": True, "written": [str(skill_path), str(mcp_path)]}


def _setup_codex(
    root: Path,
    *,
    write_codex_config: bool,
    codex_config_path: Optional[str | Path],
) -> Dict[str, Any]:
    agents_path = root / "AGENTS.md"
    section = "\n".join(
        [
            CODEX_START,
            _render_template("codex.md"),
            CODEX_END,
            "",
        ]
    )
    existing = agents_path.read_text(encoding="utf-8") if agents_path.exists() else ""
    next_text = _replace_marked_section(existing, section)
    _write_text_if_changed(agents_path, next_text)
    result: Dict[str, Any] = {
        "ok": True,
        "written": [str(agents_path)],
        "codex_config_snippet": CODEX_CONFIG_SNIPPET,
        "codex_config_written": False,
    }
    if write_codex_config:
        config_path = Path(codex_config_path or Path.home() / ".codex" / "config.toml").expanduser()
        before = config_path.read_text(encoding="utf-8") if config_path.exists() else ""
        after = _merge_codex_config(before)
        backup_path = None
        if config_path.exists() and before != after:
            backup_path = config_path.with_suffix(config_path.suffix + ".agentcanvas.bak")
            shutil.copy2(config_path, backup_path)
        _write_text_if_changed(config_path, after)
        result["codex_config_written"] = True
        result["codex_config_path"] = str(config_path)
        result["codex_config_backup"] = str(backup_path) if backup_path else None
        result["codex_config_diff"] = "".join(
            difflib.unified_diff(
                before.splitlines(True),
                after.splitlines(True),
                fromfile="before",
                tofile="after",
            )
        )
    return result


def _setup_cursor(root: Path) -> Dict[str, Any]:
    rule_path = root / ".cursor" / "rules" / "agentcanvas.mdc"
    _write_text_if_changed(rule_path, _render_template("cursor.mdc"))
    mcp_path = root / ".cursor" / "mcp.json"
    _merge_mcp_json(mcp_path)
    return {"ok": True, "written": [str(rule_path), str(mcp_path)]}


def _setup_antigravity(root: Path) -> Dict[str, Any]:
    return {
        "ok": True,
        "written": [],
        "message": "Antigravity adapter is experimental; copy the rule and MCP snippet manually.",
        "rules": _render_template("generic.md"),
        "mcp": {"agentcanvas": MCP_ENTRY},
        "workspace": str(root),
    }


def _setup_generic(root: Path) -> Dict[str, Any]:
    path = root / "AGENT_CANVAS.md"
    _write_text_if_changed(path, _render_template("generic.md"))
    return {"ok": True, "written": [str(path)]}


def _normalize_agent(agent: str) -> str:
    selected = str(agent or "").strip().lower()
    if selected not in SUPPORTED_AGENTS:
        raise AdapterSetupError(
            "UNSUPPORTED_AGENT",
            "unsupported agent",
            details={"agent": agent, "supported": sorted(SUPPORTED_AGENTS)},
        )
    return selected


def _render_template(name: str) -> str:
    template = _template_text(name)
    return (
        template.replace("{shared_core}", _template_text("shared-core.md").strip())
        .replace("{header}", OWNERSHIP_HEADER)
        .rstrip()
        + "\n"
    )


def _template_text(name: str) -> str:
    return (
        resources.files("agentcanvas")
        .joinpath("templates")
        .joinpath("adapters")
        .joinpath(name)
        .read_text(encoding="utf-8")
    )


def _load_marker_data() -> Dict[str, Any]:
    text = (
        resources.files("agentcanvas")
        .joinpath("templates")
        .joinpath("agent_markers.json")
        .read_text(encoding="utf-8")
    )
    payload = json.loads(text)
    return payload if isinstance(payload, dict) else {}


def _merge_mcp_json(path: Path) -> None:
    payload: Dict[str, Any] = {}
    if path.exists():
        try:
            existing = json.loads(path.read_text(encoding="utf-8"))
        except ValueError:
            existing = {}
        if isinstance(existing, dict):
            payload = existing
    servers = payload.get("mcpServers")
    if not isinstance(servers, dict):
        servers = {}
    servers["agentcanvas"] = dict(MCP_ENTRY)
    payload["mcpServers"] = servers
    atomic_write_json(path, payload)


def _replace_marked_section(existing: str, section: str) -> str:
    if CODEX_START in existing and CODEX_END in existing:
        start = existing.index(CODEX_START)
        end = existing.index(CODEX_END, start) + len(CODEX_END)
        prefix = existing[:start].rstrip()
        suffix = existing[end:].lstrip("\n")
        pieces = []
        if prefix:
            pieces.append(prefix)
        pieces.append(section.rstrip())
        if suffix:
            pieces.append(suffix.rstrip())
        return "\n\n".join(pieces).rstrip() + "\n"
    if existing.strip():
        return existing.rstrip() + "\n\n" + section
    return section


def _merge_codex_config(existing: str) -> str:
    if "[mcp_servers.agentcanvas]" in existing:
        return existing if existing.endswith("\n") else existing + "\n"
    if existing.strip():
        return existing.rstrip() + "\n\n" + CODEX_CONFIG_SNIPPET + "\n"
    return CODEX_CONFIG_SNIPPET + "\n"


def _write_text_if_changed(path: Path, text: str) -> None:
    if path.exists():
        try:
            if path.read_text(encoding="utf-8") == text:
                return
        except OSError:
            pass
    atomic_write_text(path, text)
