#!/usr/bin/env python3
"""Render the shared bootstrap prompt into the frontend source tree."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from agentcanvas.bootstrap import build_landing_bootstrap_prompt  # noqa: E402

DEFAULT_OUTPUT = PROJECT_ROOT / "frontend" / "src" / "lib" / "landingBootstrapPrompt.ts"
SOURCE_TEMPLATE = "agentcanvas/templates/bootstrap_prompt.md"


def render_typescript(prompt: str) -> str:
    return (
        "// Generated by scripts/render_frontend_bootstrap_prompt.py.\n"
        "// Do not edit by hand; update agentcanvas/templates/bootstrap_prompt.md instead.\n\n"
        f"export const LANDING_BOOTSTRAP_PROMPT_SOURCE = {json.dumps(SOURCE_TEMPLATE)}\n"
        f"export const LANDING_BOOTSTRAP_PROMPT = {json.dumps(prompt, ensure_ascii=True)}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_typescript(build_landing_bootstrap_prompt()), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
