#!/usr/bin/env python3
import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_WORKSPACE = PROJECT_ROOT / "examples" / "sample-js-app"


def run_agentcanvas(args, cwd):
    env = os.environ.copy()
    pythonpath = env.get("PYTHONPATH")
    env["PYTHONPATH"] = (
        str(PROJECT_ROOT)
        if not pythonpath
        else str(PROJECT_ROOT) + os.pathsep + pythonpath
    )
    return subprocess.run(
        [sys.executable, "-m", "agentcanvas", *args],
        cwd=cwd,
        env=env,
        text=True,
        capture_output=True,
        timeout=20,
    )


def print_result(label, completed):
    print(f"\n== {label} ==")
    print(f"exit: {completed.returncode}")
    if completed.stdout:
        print(completed.stdout.rstrip())
    if completed.stderr:
        print(completed.stderr.rstrip(), file=sys.stderr)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Run a non-destructive AgentCanvas MVP smoke test."
    )
    parser.add_argument(
        "workspace",
        nargs="?",
        default=str(DEFAULT_WORKSPACE),
        help="Workspace fixture to copy into a temporary directory.",
    )
    args = parser.parse_args(argv)

    source_workspace = Path(args.workspace).resolve()
    if not source_workspace.is_dir():
        parser.error(f"workspace does not exist: {source_workspace}")

    with tempfile.TemporaryDirectory(prefix="agentcanvas-smoke-") as temp_root:
        temp_root_path = Path(temp_root)
        workspace = temp_root_path / source_workspace.name
        shutil.copytree(source_workspace, workspace)
        print(f"workspace copy: {workspace}")

        index_result = run_agentcanvas(["index", str(workspace)], cwd=temp_root)
        print_result("agentcanvas index", index_result)
        if index_result.returncode != 0:
            return index_result.returncode

        ir_path = workspace / ".agentcanvas" / "workflow.ir.json"
        if not ir_path.is_file():
            print(f"missing expected IR: {ir_path}", file=sys.stderr)
            return 1
        json.loads(ir_path.read_text(encoding="utf-8"))

        pending_dir = workspace / ".agentcanvas" / "pending"
        pending_dir.mkdir(parents=True, exist_ok=True)
        (pending_dir / "smoke-change.md").write_text(
            "# Smoke Change\n\nGenerated by scripts/smoke_mvp.py.\n",
            encoding="utf-8",
        )
        (pending_dir / "smoke-change.json").write_text(
            json.dumps({"id": "smoke-change", "title": "Smoke change"}),
            encoding="utf-8",
        )

        pending_result = run_agentcanvas(["pending", str(workspace)], cwd=temp_root)
        print_result("agentcanvas pending", pending_result)
        if pending_result.returncode != 0:
            return pending_result.returncode
        if "smoke-change.md" not in pending_result.stdout:
            print("pending output did not include smoke-change.md", file=sys.stderr)
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
